### ISSUE TITLE
cant get to work

### ISSUE THREAD

**Issue by KanJyro** [Doliman100/ForzaTech-extraction-tools#1]
cant get to work, is there a video showing the process of converting FH5 model bin to work in 3dsimed

**Comment by Doliman100** [comment]
What error does it print? I haven't met such a video.

**Comment by KanJyro** [comment]
i mean i don't understand enough of how to use the tool to even get to convert the files so they can be read by 3dsimed. the instructions aren't very clear

**Comment by KanJyro** [comment]
like i have the unencrypted files, i got the hex editing software you recommended for the process, i cant for the life of me figure out how to load your script to the software. i'm a complete novice in this kind of stuff

**Comment by Doliman100** [comment]
1. Install the latest LTS [Node.js](https://nodejs.org/en/download).
	a. It's tested on Node.js v18.14.0, so report any compatibility issues if they are.
2. Download the repository using the green button on [the main page](https://github.com/Doliman100/ForzaTech-extraction-tools) **"<> Code" > Local > Download ZIP**.
3. Unzip it to any directory, for example "C:\Users\Doliman100\Downloads\".
4. Rename the **.carbin** file you are interested in to **.carbin.bak**.
5. Run the command from README.md:
```
node C:\Users\Doliman100\Downloads\ForzaTech-extraction-tools-main\scripts\carbin_converter.js "D:\games\rips\FH5\media\Cars\NUL_Car_00\NUL_Car_00.carbin.bak"
```
6. Import the resulting **NUL_Car_00.carbin** to 3DSimED.

**Comment by H3rcu1es** [comment]
could import the car but tires are missing

**Comment by Doliman100** [comment]
> could import the car but tires are missing

This question is beyond this repository and relates to 3DSimED. It's better to ask such questions in specific places, like [GameModels Community](https://discord.gg/XkCQGws)

**Comment by H3rcu1es** [comment]
Ow ok thanks .  I was wondering why your tires are perfectly appeared  but mine is missing .
