### ISSUE TITLE
Buffer out of bounds

### ISSUE THREAD

**Issue by Pimmiecreep** [Doliman100/ForzaTech-extraction-tools#3]
Error when trying to convert .modelbin using the tool. 

```
Warning: Unknown root chunk type: 30050.
node:internal/buffer:86
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
          ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (node:internal/buffer:86:11)
    at Buffer.readUInt32LE (node:internal/buffer:222:5)
    at Reader.readArray (file:///C:/Users/Pim/Downloads/FORZA/ForzaTech-extraction-tools-main/scripts/carbin_converter.js:35:35)
    at file:///C:/Users/Pim/Downloads/FORZA/ForzaTech-extraction-tools-main/scripts/carbin_converter.js:121:22 {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}

Node.js v20.15.1
```

Not a pro at this, I reinstalled Node.js and the Extraction Tools

**Comment by Doliman100** [comment]
There is no `.modelbin` converter in this repository. I don't know why you passed a `.modelbin` file to the `.carbin` converter. It makes no sense.

**Comment by Pimmiecreep** [comment]
Some guy told me it could work and that he did it? Is there any other way of converting .modelling?

**Comment by Doliman100** [comment]
Why do you need it? The `.modelbin` imports fine in 3DSimED except for material error messages. I tried to fix it, but without success. I don't know any `.modelbin` downgrade tool.

**Comment by Pimmiecreep** [comment]
Hmmm, that's weird, I need t
It to import rims from forza5. But when I load it in 3Dsim it loads the material errors but no mesh

**Comment by Doliman100** [comment]
Send me the `.modelbin` file.

**Comment by Pimmiecreep** [comment]
[VOR_VFF102.zip](https://github.com/user-attachments/files/16190978/VOR_VFF102.zip)

**Comment by Doliman100** [comment]
![image](https://github.com/user-attachments/assets/edea68b0-4afe-4903-9930-94f6a72e2821)
This file imports fine.

**Comment by Pimmiecreep** [comment]
What is happening to my file then? Because now im trying to convert a .carbin file and it converts but im importing no mesh

**Comment by Doliman100** [comment]
https://github.com/Doliman100/ForzaTech-extraction-tools/issues/3#issuecomment-2225129802 I imported **your** file, so the file is ok.
Maybe you don't have right folder structure? Cars folder should be in `...\media\Cars\` and wheels should be in `...\media\Cars\_library\scene\wheels\`.

**Comment by Pimmiecreep** [comment]
And from there i should import to 3DSim right?

**Comment by Doliman100** [comment]
Yes.

**Comment by Pimmiecreep** [comment]
Okay, Thankyou! Im sorry if i bothered you. But thankyou for your help!

**Comment by SakuraiKira** [comment]
hello,it's there any tutorial to get forza horizon 5's texture. 

I follow your step to extra a car from FH5,but don't know how to get textures ,  there's no result by serach from google (maybe i missed it but i can't find some help）.

**Comment by Doliman100** [comment]
I don't think the texture question has any relation to this issue.
