### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by batkriso** [Doliman100/ForzaTech-extraction-tools#4]
I'm getting an index error when trying to import "body_a.modelbin", everything else imports without any hiccups
![Capture](https://github.com/user-attachments/assets/cad23fab-c479-4ee4-b2e8-b8ef6767997b)

**Comment by Doliman100** [comment]
Send the modelbin file here.

**Comment by batkriso** [comment]
[body_a.zip](https://github.com/user-attachments/files/17450717/body_a.zip)

**Comment by Doliman100** [comment]
What car is it?

**Comment by batkriso** [comment]
765LT. From FH5 I think, not too sure since the original download didnt say anything. Its in Game Models discord, game request channel, you can check it out there

**Comment by Doliman100** [comment]
Fixed in a8f0f0d4e0144a3b95a5f04f52de494b63509416. Please, confirm this.

**Comment by batkriso** [comment]
fix **confirmed** 👍🏻
