### ISSUE TITLE
Blender script not working 

### ISSUE THREAD

**Issue by LoaderStream** [Doliman100/ForzaTech-extraction-tools#5]
Hey i am Trying to get 3d model in blender can you explain how that works in detail i try your instruction but its not working for me.

**Comment by Doliman100** [comment]
What error does it print?

**Comment by LoaderStream** [comment]
I try everything but when i try open python file its just open and close in second and can i know the blender process in simple words like how can i install this extractor to blender

**Comment by Doliman100** [comment]
Read the first sentence of the tutorial: https://github.com/Doliman100/ForzaTech-extraction-tools#how-to-use
What happens when you press Run Script?

**Comment by LoaderStream** [comment]
When i try to open its just pop up and close in second

**Comment by LoaderStream** [comment]
I cant able to edit the script i have windows 11

**Comment by Doliman100** [comment]
Write here the part of the tutorial where it says to open something. I don't see it there.

**Comment by LoaderStream** [comment]
Paste the carbin_importer.py contents into Blender 4.2 Scripting Text Editor and Run Script.
game_path is the absolute path to the game rip root folder with unzipped cars, tires, materials, shaders and textures. The rip must have the original folder structure

**Comment by LoaderStream** [comment]
Run the script

**Comment by Doliman100** [comment]
Follow the tutorial step by step. Take a screenshot of the window where you pasted the file contents into Blender.

**Comment by LoaderStream** [comment]
Ok

**Comment by LoaderStream** [comment]
(https://drive.google.com/file/d/13yJSx0DTZXuFe_sc3pqn_7gd4qIrpJNd/view?usp=sharing)

check this image

**Comment by Doliman100** [comment]
I don't see a Blender window on your screenshot.

**Comment by LoaderStream** [comment]
https://drive.google.com/file/d/18a-qZAyN8QU8hkRKmJLkVGhdHBI5r1Kd/view?usp=sharing, https://drive.google.com/file/d/1D0eniHNQaptudYs9tviQi3y_Szbr2ZyR/view?usp=sharing

**Comment by Doliman100** [comment]
Why are you keep ignoring the beginning of the tutorial? I don't see the file content pasted into the Blender Scripting window.

**Comment by LoaderStream** [comment]
i did it after this the location process is complicated!
https://drive.google.com/file/d/1VqUe47pTYJ7BovhzfBUmUOezD3Vsu5Yb/view?usp=sharing

**Comment by Doliman100** [comment]
Just follow the tutorial. I can't help you if you don't have a proper question. You can ask about printed errors if you can't fix them yourself.
